# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hades.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hades.proto',
  package='hades',
  syntax='proto3',
  serialized_options=b'\n\032com.github.chayward1.hadesZ\006/hades',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bhades.proto\x12\x05hades\"L\n\x04Zone\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07updated\x18\x02 \x01(\x03\x12\x13\n\x0btemperature\x18\x03 \x01(\x05\x12\x10\n\x08humidity\x18\x04 \x01(\x05\x32N\n\x05Hades\x12\"\n\x04Read\x12\x0b.hades.Zone\x1a\x0b.hades.Zone0\x01\x12!\n\x05Write\x12\x0b.hades.Zone\x1a\x0b.hades.ZoneB$\n\x1a\x63om.github.chayward1.hadesZ\x06/hadesb\x06proto3'
)




_ZONE = _descriptor.Descriptor(
  name='Zone',
  full_name='hades.Zone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hades.Zone.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updated', full_name='hades.Zone.updated', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='hades.Zone.temperature', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='hades.Zone.humidity', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['Zone'] = _ZONE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Zone = _reflection.GeneratedProtocolMessageType('Zone', (_message.Message,), {
  'DESCRIPTOR' : _ZONE,
  '__module__' : 'hades_pb2'
  # @@protoc_insertion_point(class_scope:hades.Zone)
  })
_sym_db.RegisterMessage(Zone)


DESCRIPTOR._options = None

_HADES = _descriptor.ServiceDescriptor(
  name='Hades',
  full_name='hades.Hades',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=100,
  serialized_end=178,
  methods=[
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='hades.Hades.Read',
    index=0,
    containing_service=None,
    input_type=_ZONE,
    output_type=_ZONE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Write',
    full_name='hades.Hades.Write',
    index=1,
    containing_service=None,
    input_type=_ZONE,
    output_type=_ZONE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HADES)

DESCRIPTOR.services_by_name['Hades'] = _HADES

# @@protoc_insertion_point(module_scope)
